version: "3.9"
services:
  postgres:
    image: postgres:16
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: orders
    ports:
      - "5433:5432"
        
  rabbitmq:
    image: rabbitmq:3-management
    ports: ["5672:5672","15672:15672"]